/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<bigint, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityCodes {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  label_en: string;
  label_km: string;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ApiTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  label: string;
  last_used_at: Timestamp | null;
  prefix: string;
  revoked_at: Timestamp | null;
  scopes: string[];
  token_hash: string;
  user_id: string;
}

export interface ApprovalEvents {
  actor_name: string;
  approval_id: string;
  assignee_id: string | null;
  assignee_permission_ok: boolean | null;
  at: Generated<Timestamp>;
  channel: string | null;
  event: string;
  id: Generated<string>;
  seq: Generated<Int8>;
}

export interface ApprovalPolicies {
  chain: string[];
  channels_allowed: Generated<string[]>;
  created_at: Generated<Timestamp>;
  fallback_approver_id: string | null;
  kind: string;
  label_en: string;
  label_km: string;
  required_permission: string;
  sla_minutes: number;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Approvals {
  assignee_id: string | null;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decided_channel: string | null;
  decision_note: string | null;
  due_at: Timestamp;
  escalation_level: Generated<number>;
  id: Generated<string>;
  kind: string;
  on_approve: Generated<Json>;
  outcome: string | null;
  requested_by: string;
  required_permission: string;
  snapshot: Generated<Json>;
  status: Generated<string>;
  subject_hash: string;
  subject_id: string;
  subject_type: string;
  subject_version: number;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AttendanceSessions {
  auto_closed: Generated<boolean>;
  channel: string;
  correction_reason: string | null;
  created_at: Generated<Timestamp>;
  end_channel: string | null;
  ended_at: Timestamp | null;
  flag_reason: string | null;
  flagged: Generated<boolean>;
  id: Generated<string>;
  started_at: Timestamp;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
}

export interface AuditChanges {
  actor_id: string | null;
  actor_name: string | null;
  changed_at: Generated<Timestamp>;
  channel: string | null;
  id: Generated<Int8>;
  new_row: Json | null;
  old_row: Json | null;
  op: string;
  request_id: string | null;
  row_id: string | null;
  table_name: string;
}

export interface AuditEvents {
  action: string;
  actor_id: string | null;
  actor_name: string;
  actor_type: string;
  channel: string;
  error_code: string | null;
  id: Generated<Int8>;
  input: Generated<Json>;
  mcp_client: string | null;
  mcp_grant_id: string | null;
  occurred_at: Generated<Timestamp>;
  on_behalf_of: string | null;
  outcome: Generated<string>;
  request_id: string;
  subject_id: string | null;
  subject_type: string | null;
}

export interface ChangeOrderLines {
  change_order_id: string;
  created_at: Generated<Timestamp>;
  description_en: string;
  description_km: string | null;
  discount_bp: Generated<number>;
  id: Generated<string>;
  kind: string;
  line_cost_minor: Int8;
  line_price_minor: Int8;
  list_price_minor: Int8 | null;
  position: number;
  qty_milli: number;
  quoted_minutes: number | null;
  rate_card_item_id: string | null;
  service_code: string | null;
  unit_cost_minor: Int8;
  unit_price_minor: Int8;
  updated_at: Generated<Timestamp>;
}

export interface ChangeOrders {
  accepted_at: Timestamp | null;
  accepted_by: string | null;
  below_floor: Generated<boolean>;
  content_sha256: Generated<string>;
  created_at: Generated<Timestamp>;
  currency: string;
  discount_minor: Generated<Int8>;
  fee_cost_minor: Generated<Int8>;
  fee_margin_bp: number | null;
  fee_price_minor: Generated<Int8>;
  id: Generated<string>;
  number: number;
  project_id: string;
  pt_cost_minor: Generated<Int8>;
  pt_markup_bp: number | null;
  pt_price_minor: Generated<Int8>;
  scope_id: string;
  scope_period_id: string | null;
  sent_at: Timestamp | null;
  sent_by: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  title: string;
  total_minor: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ClientGateExemptions {
  client_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp;
  decided_by: string;
  gate: string;
  id: Generated<string>;
  reason: string;
  revoked_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Clients {
  account_lead_id: string;
  airtable_id: string | null;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  industry: string | null;
  legacy: Generated<boolean>;
  name: string;
  name_km: string | null;
  per_period_gates: Generated<boolean>;
  po_required: Generated<boolean>;
  team_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface CloseReasons {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  kind: string;
  label_en: string;
  label_km: string;
  legacy_only: Generated<boolean>;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Contacts {
  airtable_id: string | null;
  archived_at: Timestamp | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  phone: string | null;
  telegram: string | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Deals {
  airtable_id: string | null;
  client_id: string;
  close_note: string | null;
  close_reason_code: string | null;
  close_reason_kind: string | null;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  expected_close_on: string | null;
  expected_value_minor: Int8 | null;
  id: Generated<string>;
  legacy: Generated<boolean>;
  owner_id: string;
  stage: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DealStageHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  close_reason_code: string | null;
  deal_id: string;
  from_stage: string | null;
  id: Generated<string>;
  note: string | null;
  seq: Generated<Int8>;
  to_stage: string;
}

export interface EngagementTypes {
  active: Generated<boolean>;
  code: string;
  commercial_model: string;
  created_at: Generated<Timestamp>;
  fee_margin_floor_bp: Generated<number>;
  id: Generated<string>;
  label_en: string;
  label_km: string;
  passthrough_markup_floor_bp: number | null;
  passthrough_markup_warn_bp: Generated<number>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface FxRates {
  base: Generated<string>;
  created_at: Generated<Timestamp>;
  entered_by: string | null;
  id: Generated<string>;
  quote: Generated<string>;
  rate_date: string;
  rate_micros: Int8;
  source: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface GateBypasses {
  approval_id: string | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  close_cause: string | null;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  gates: string[];
  id: Generated<string>;
  legacy: Generated<boolean>;
  named_owner_id: string;
  project_id: string;
  reason: string;
  requested_by: string;
  review_month: string | null;
  review_outcome: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface GiveawayEntries {
  adjusts_entry_id: string | null;
  amount_usd_minor: Int8;
  attributed_month: string;
  client_id: string;
  created_at: Generated<Timestamp>;
  fx_rate_micros: Int8;
  id: Generated<string>;
  kind: string;
  note: string | null;
  occurred_on: string;
  project_id: string | null;
  source_id: string;
  source_type: string;
}

export interface Holidays {
  created_at: Generated<Timestamp>;
  holiday_date: string;
  id: Generated<string>;
  name_en: string;
  name_km: string;
  source: string;
  updated_at: Generated<Timestamp>;
  verified: Generated<boolean>;
  verified_at: Timestamp | null;
  verified_by: string | null;
  version: Generated<number>;
}

export interface InfluencerAssignments {
  active: Generated<boolean>;
  contracted_posts: number;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string | null;
  id: Generated<string>;
  influencer_id: string;
  notes: string | null;
  per_post_passthrough_minor: Int8 | null;
  project_id: string;
  scope_item_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Influencers {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  display_name: string;
  handles: Generated<Json>;
  id: Generated<string>;
  notes: string | null;
  phone: string | null;
  telegram: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface InfluencerWorkLogs {
  approval_id: string | null;
  assignment_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  id: Generated<string>;
  ip: string | null;
  link_id: string;
  metrics: Generated<Json>;
  note: string | null;
  oos_approval_id: string | null;
  oos_outcome: string | null;
  over_quantity: Generated<boolean>;
  post_url: string;
  posted_on: string;
  proof_urls: Generated<string[]>;
  status: Generated<string>;
  submitted_at: Timestamp;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  version: Generated<number>;
}

export interface LeaveRequests {
  approval_id: string | null;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  end_date: string;
  half_day: string | null;
  id: Generated<string>;
  leave_type: string;
  reason: string | null;
  start_date: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
}

export interface LeaveTypes {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  half_day_allowed: Generated<boolean>;
  label_en: string;
  label_km: string;
  paid: Generated<boolean>;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface McpConfirmTokens {
  approval_id: string;
  approval_version: number;
  created_at: Generated<Timestamp>;
  decision: string;
  expires_at: Timestamp;
  grant_id: string;
  id: Generated<string>;
  note: string | null;
  outcome: string | null;
  subject_hash: string;
  subject_version: number;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface OauthClients {
  client_id: string;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  expires_at: Timestamp | null;
  fetched_at: Timestamp | null;
  kind: string;
  metadata: Json;
  updated_at: Generated<Timestamp>;
}

export interface OidcPayloads {
  account_id: string | null;
  client_id: string | null;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  grant_id: string | null;
  id: string;
  model: string;
  payload: Json;
  uid: string | null;
}

export interface Outbox {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event: string;
  id: Generated<Int8>;
  last_error: string | null;
  payload: Json;
  request_id: string;
}

export interface ProjectGates {
  created_at: Generated<Timestamp>;
  evidence: string | null;
  exemption_id: string | null;
  gate: string;
  id: Generated<string>;
  project_id: string;
  satisfied_at: Timestamp | null;
  satisfied_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ProjectMembers {
  created_at: Generated<Timestamp>;
  project_id: string;
  project_role: string;
  user_id: string;
}

export interface Projects {
  activated_at: Timestamp | null;
  client_id: string | null;
  created_at: Generated<Timestamp>;
  deal_id: string | null;
  engagement_type_id: string | null;
  id: Generated<string>;
  kind: string;
  name: string;
  planned_start: string;
  pm_id: string;
  project_type_id: string;
  quote_id: string | null;
  scope_id: string | null;
  status: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ProjectTypes {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  default_engagement_type_id: string;
  id: Generated<string>;
  label_en: string;
  label_km: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface QuoteLines {
  created_at: Generated<Timestamp>;
  description_en: string;
  description_km: string | null;
  discount_bp: Generated<number>;
  id: Generated<string>;
  kind: string;
  line_cost_minor: Int8;
  line_price_minor: Int8;
  list_price_minor: Int8 | null;
  per_period: Generated<boolean>;
  position: number;
  qty_milli: number;
  quote_id: string;
  quoted_minutes: number | null;
  rate_card_item_id: string | null;
  service_code: string | null;
  unit_cost_minor: Int8;
  unit_price_minor: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Quotes {
  below_floor: Generated<boolean>;
  billing_model: Generated<string>;
  client_id: string;
  content_sha256: Generated<string>;
  created_at: Generated<Timestamp>;
  currency: string;
  deal_id: string;
  discount_minor: Generated<Int8>;
  engagement_type_id: string;
  fee_cost_minor: Generated<Int8>;
  fee_margin_bp: number | null;
  fee_price_minor: Generated<Int8>;
  fx_rate_date: string | null;
  fx_rate_micros: Int8 | null;
  id: Generated<string>;
  owner_id: string;
  pdf_status: string | null;
  period_months: number | null;
  project_type_id: string | null;
  pt_cost_minor: Generated<Int8>;
  pt_markup_bp: number | null;
  pt_price_minor: Generated<Int8>;
  rate_card_id: string | null;
  rejected_reason: string | null;
  send_on_approval: Generated<boolean>;
  sent_at: Timestamp | null;
  sent_by: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  supersedes_quote_id: string | null;
  terms: string | null;
  title: string;
  total_minor: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  valid_until: string | null;
  version: Generated<number>;
  version_no: Generated<number>;
  win_reason_code: string | null;
}

export interface RateCardItems {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  label_en: string;
  label_km: string;
  rate_card_id: string;
  service_code: string;
  unit: string;
  unit_cost_minor: Int8;
  unit_price_minor: Int8;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface RateCards {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ScopeItems {
  created_at: Generated<Timestamp>;
  description_en: string;
  description_km: string | null;
  id: Generated<string>;
  kind: string;
  line_price_minor: Int8;
  per_period: Generated<boolean>;
  qty_milli: number;
  quoted_minutes: number | null;
  scope_id: string;
  scope_period_id: string | null;
  service_code: string | null;
  source_id: string;
  source_type: string;
  unit_price_minor: Int8;
}

export interface ScopePeriods {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  period_end: string;
  period_no: number;
  period_start: string;
  scope_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Scopes {
  billing_model: string;
  client_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  fx_rate_micros: Int8;
  id: Generated<string>;
  period_months: number | null;
  quote_id: string;
  starts_on: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  step_up_at: Timestamp | null;
  token_hash: string;
  totp_verified: Generated<boolean>;
  user_agent: string | null;
  user_id: string;
}

export interface Settings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface TaskDependencies {
  created_at: Generated<Timestamp>;
  depends_on_id: string;
  task_id: string;
}

export interface TaskRounds {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  note: string | null;
  oos_approval_id: string | null;
  quality_approval_id: string | null;
  requested_by: string;
  rework_minutes: number | null;
  round: number;
  task_id: string;
}

export interface Tasks {
  client_facing: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  done_at: Timestamp | null;
  due_date: string;
  estimate_minutes: number;
  estimate_source: Generated<string>;
  id: Generated<string>;
  non_deliverable: Generated<boolean>;
  oos_approval_id: string | null;
  oos_decision: string | null;
  oos_status: Generated<string>;
  owner_id: string;
  project_id: string;
  quality_approval_id: string | null;
  rank: Generated<number>;
  revision_oos_approval_id: string | null;
  revision_round: Generated<number>;
  scope_item_id: string | null;
  sent_reference: string | null;
  sent_to_client_at: Timestamp | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  template_item_id: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface TaskTemplateItems {
  client_facing: Generated<boolean>;
  created_at: Generated<Timestamp>;
  depends_on_keys: Generated<string[]>;
  estimate_minutes: number;
  id: Generated<string>;
  key: string;
  offset_days: number;
  position: number;
  role_hint: string | null;
  service_code: string | null;
  template_id: string;
  title_en: string;
  title_km: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TaskTemplates {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  project_type_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Teams {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  name_km: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TelegramActions {
  approval_id: string | null;
  created_at: Generated<Timestamp>;
  decision: string;
  expires_at: Timestamp;
  kind: Generated<string>;
  outcome: string | null;
  payload: Json | null;
  subject_version: number;
  telegram_user_id: Int8;
  token: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface TelegramLinkCodes {
  code_hash: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface TimeAllocations {
  activity_code: string | null;
  created_at: Generated<Timestamp>;
  deal_id: string | null;
  id: Generated<string>;
  minutes: number;
  note: string | null;
  project_id: string | null;
  source: string;
  status: Generated<string>;
  target_key: Generated<string | null>;
  target_type: string;
  task_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
  work_date: string;
}

export interface TimesheetWeeks {
  confirmed_at: Timestamp | null;
  confirmed_channel: string | null;
  created_at: Generated<Timestamp>;
  draft_hash: string | null;
  escalated_at: Timestamp | null;
  first_confirmed_at: Timestamp | null;
  id: Generated<string>;
  opened_at: Timestamp | null;
  prefill_minutes: number | null;
  reminded_at: Timestamp | null;
  reopen_count: Generated<number>;
  reopen_reason: string | null;
  reopened_at: Timestamp | null;
  reopened_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
  week_start: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  role: string;
  user_id: string;
}

export interface Users {
  active: Generated<boolean>;
  cost_rate_minor: Int8 | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  display_name_km: string | null;
  email: string;
  failed_logins: Generated<number>;
  id: Generated<string>;
  locale: Generated<string>;
  locked_until: Timestamp | null;
  manager_id: string | null;
  password_hash: string;
  team_id: string | null;
  telegram_user_id: Int8 | null;
  totp_enabled: Generated<boolean>;
  totp_failures: Generated<number>;
  totp_last_step: Int8 | null;
  totp_secret_enc: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weekly_capacity_minutes: Generated<number>;
  working_days: Generated<number[]>;
}

export interface VInfluencerWorkApproved {
  approved_at: Timestamp | null;
  approved_by: string | null;
  assignment_id: string | null;
  id: string | null;
  influencer_id: string | null;
  metrics: Json | null;
  oos_outcome: string | null;
  over_quantity: boolean | null;
  post_url: string | null;
  posted_on: string | null;
  project_id: string | null;
  scope_item_id: string | null;
}

export interface WorkLogLinks {
  assignment_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Timestamp;
  issued_by: string;
  max_submissions: Generated<number>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  status: Generated<string>;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DB {
  activity_codes: ActivityCodes;
  api_tokens: ApiTokens;
  approval_events: ApprovalEvents;
  approval_policies: ApprovalPolicies;
  approvals: Approvals;
  attendance_sessions: AttendanceSessions;
  audit_changes: AuditChanges;
  audit_events: AuditEvents;
  change_order_lines: ChangeOrderLines;
  change_orders: ChangeOrders;
  client_gate_exemptions: ClientGateExemptions;
  clients: Clients;
  close_reasons: CloseReasons;
  contacts: Contacts;
  deal_stage_history: DealStageHistory;
  deals: Deals;
  engagement_types: EngagementTypes;
  fx_rates: FxRates;
  gate_bypasses: GateBypasses;
  giveaway_entries: GiveawayEntries;
  holidays: Holidays;
  influencer_assignments: InfluencerAssignments;
  influencer_work_logs: InfluencerWorkLogs;
  influencers: Influencers;
  leave_requests: LeaveRequests;
  leave_types: LeaveTypes;
  mcp_confirm_tokens: McpConfirmTokens;
  oauth_clients: OauthClients;
  oidc_payloads: OidcPayloads;
  outbox: Outbox;
  project_gates: ProjectGates;
  project_members: ProjectMembers;
  project_types: ProjectTypes;
  projects: Projects;
  quote_lines: QuoteLines;
  quotes: Quotes;
  rate_card_items: RateCardItems;
  rate_cards: RateCards;
  scope_items: ScopeItems;
  scope_periods: ScopePeriods;
  scopes: Scopes;
  sessions: Sessions;
  settings: Settings;
  task_dependencies: TaskDependencies;
  task_rounds: TaskRounds;
  task_template_items: TaskTemplateItems;
  task_templates: TaskTemplates;
  tasks: Tasks;
  teams: Teams;
  telegram_actions: TelegramActions;
  telegram_link_codes: TelegramLinkCodes;
  time_allocations: TimeAllocations;
  timesheet_weeks: TimesheetWeeks;
  user_roles: UserRoles;
  users: Users;
  v_influencer_work_approved: VInfluencerWorkApproved;
  work_log_links: WorkLogLinks;
}
