/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<bigint, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditChanges {
  actor_id: string | null;
  actor_name: string | null;
  changed_at: Generated<Timestamp>;
  channel: string | null;
  id: Generated<Int8>;
  new_row: Json | null;
  old_row: Json | null;
  op: string;
  request_id: string | null;
  row_id: string | null;
  table_name: string;
}

export interface AuditEvents {
  action: string;
  actor_id: string | null;
  actor_name: string;
  actor_type: string;
  channel: string;
  error_code: string | null;
  id: Generated<Int8>;
  input: Generated<Json>;
  mcp_client: string | null;
  occurred_at: Generated<Timestamp>;
  on_behalf_of: string | null;
  outcome: Generated<string>;
  request_id: string;
  subject_id: string | null;
  subject_type: string | null;
}

export interface Clients {
  account_lead_id: string;
  airtable_id: string | null;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  industry: string | null;
  legacy: Generated<boolean>;
  name: string;
  name_km: string | null;
  po_required: Generated<boolean>;
  team_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface CloseReasons {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  kind: string;
  label_en: string;
  label_km: string;
  legacy_only: Generated<boolean>;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Contacts {
  airtable_id: string | null;
  archived_at: Timestamp | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  phone: string | null;
  telegram: string | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Deals {
  airtable_id: string | null;
  client_id: string;
  close_note: string | null;
  close_reason_code: string | null;
  close_reason_kind: string | null;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  expected_close_on: Timestamp | null;
  expected_value_minor: Int8 | null;
  id: Generated<string>;
  legacy: Generated<boolean>;
  owner_id: string;
  stage: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DealStageHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  close_reason_code: string | null;
  deal_id: string;
  from_stage: string | null;
  id: Generated<string>;
  note: string | null;
  seq: Generated<Int8>;
  to_stage: string;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event: string;
  id: Generated<Int8>;
  payload: Json;
  request_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  totp_verified: Generated<boolean>;
  user_agent: string | null;
  user_id: string;
}

export interface Settings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface Teams {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  name_km: string | null;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  role: string;
  user_id: string;
}

export interface Users {
  active: Generated<boolean>;
  cost_rate_minor: Int8 | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  display_name_km: string | null;
  email: string;
  failed_logins: Generated<number>;
  id: Generated<string>;
  locale: Generated<string>;
  locked_until: Timestamp | null;
  manager_id: string | null;
  password_hash: string;
  team_id: string | null;
  telegram_user_id: Int8 | null;
  totp_enabled: Generated<boolean>;
  totp_last_step: Int8 | null;
  totp_secret_enc: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  weekly_capacity_minutes: Generated<number>;
  working_days: Generated<number[]>;
}

export interface DB {
  audit_changes: AuditChanges;
  audit_events: AuditEvents;
  clients: Clients;
  close_reasons: CloseReasons;
  contacts: Contacts;
  deal_stage_history: DealStageHistory;
  deals: Deals;
  outbox: Outbox;
  sessions: Sessions;
  settings: Settings;
  teams: Teams;
  user_roles: UserRoles;
  users: Users;
}
