// Stable error codes (RFC 9457 problem types). Every code has en + km text in i18n/*.json.
export const ERROR_STATUS = {
  VALIDATION: 422,
  UNAUTHENTICATED: 401,
  TOTP_REQUIRED: 401,
  TOTP_INVALID: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  STALE_VERSION: 409,
  INVALID_TRANSITION: 409,
  CLOSE_REASON_REQUIRED: 422,
  CLOSE_REASON_INVALID: 422,
  WIN_REQUIRES_QUOTE: 409,
  REOPEN_REASON_REQUIRED: 422,
  CURRENCY_MISMATCH: 422,
  QUOTE_LOCKED: 409,
  QUOTE_EMPTY: 422,
  MARGIN_BELOW_FLOOR: 409,
  FX_RATE_MISSING: 409,
  SELF_APPROVAL: 403,
  ALREADY_DECIDED: 409,
  DECIDE_IN_APP: 403,
  STEP_UP_REQUIRED: 401,
  WIN_REASON_REQUIRED: 422,
  CHANGE_ORDER_NOT_ADDITIVE: 422,
  GATE_BLOCKED: 409,
  GATE_EXEMPTION_REQUIRED: 422,
  BYPASS_INVALID: 422,
  TASK_INCOMPLETE: 422,
  OUT_OF_SCOPE_REQUIRED: 422,
  DEPENDENCY_CYCLE: 422,
  DEPENDENCY_OPEN: 409,
  // --- S4 ---
  OOS_DECISION_REQUIRED: 409,
  REVISION_HARD_STOP: 409,
  QC_REQUIRED: 409,
  CLOCK_RUNNING: 409,
  CLOCK_NOT_RUNNING: 409,
  TIME_OVERLAP: 409,
  TIMESHEET_CONFIRMED: 409,
  LEAVE_OVERLAP: 409,
  LINK_EXPIRED: 410,
  MCP_WRITES_DISABLED: 403,
  CONFIRM_TOKEN_INVALID: 409,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_STATUS;
export const ERROR_CODES = Object.keys(ERROR_STATUS) as ErrorCode[];

export interface Problem {
  type: string;
  title: string;
  status: number;
  code: ErrorCode;
  detail?: string;
  params?: Record<string, unknown>;
  requestId?: string;
}
